CREATE TABLE IF NOT EXISTS itineraries (
    id UUID PRIMARY KEY,
    user_id UUID REFERENCES users(id),
    title TEXT NOT NULL,
    description TEXT,
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    budget DECIMAL(10, 2) DEFAULT 0.00,
    currency VARCHAR(10) DEFAULT 'USD',
    number_of_people INT DEFAULT 1,
    likes_count INT DEFAULT 0,
    comments_count INT DEFAULT 0,
    category VARCHAR(50),
    photo_url VARCHAR(255),
    location_name TEXT,
    location_label TEXT,
    latitude DECIMAL,
    longitude DECIMAL
);